git:
  depth: 3
python:
  - "2.7"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
cache: pip
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
after_success:
  - pip install coveralls
  - pip install pytest-cov 
  - py.test --cov=dsb dsb/
  - coveralls
